### ISSUE TITLE
feature request - add files stripping 

### ISSUE THREAD

**Issue by nephaste** [teacat/chaturbate-dvr#12]
Hi 

is it possible to add a flag to command line to strip video into 1Gb video (or any other size)

when record reach 1Gb ... then start a new file 

to avoid to get a single file of 2Gb (or more) ...   :)

**Comment by YamiOdymel** [comment]
The program in 0.7 Alpha has updated for new `-s [FILESIZE_MB]` flag, usage as below:

```
> ./chaturbate-dvr -u hello -s 1024
```

`1024` for `1024 MiB` which is `1 GiB`, and later in the output log you shall see messages like these:

```
2022/09/07 18:08:43 specifying stripping limit as 1024 MiB(s)
...
2022/09/07 18:08:58 exceeded the specified stripping limit, creating new video file. (file: ./video/hello_2022-09-07_18-08-43_1.ts)
```

Make sure you redownload the program from `/bin`, 

the filesize for splitting might not be very precision (due to each chunks are not evenly divided) but atleast does the trick.
