### ISSUE TITLE
m3u8.Playlist is nil

### ISSUE THREAD

**Issue by TamaTT** [teacat/chaturbate-dvr#20]
Hi,
please what this problem means? Is it a bug?

Thanks.
Btw. Thanks a lot for this software.

![image](https://user-images.githubusercontent.com/119944809/205920450-6ab748d7-9a50-4129-ae8e-2200d289e5f1.png)

**Comment by YamiOdymel** [comment]
Maybe network issue so it didn't fetch the Playlist (of video segments) correctly, does it still occur?

**Comment by TamaTT** [comment]
> Maybe network issue so it didn't fetch the Playlist (of video segments) correctly, does it still occur?

Yes, I tried it a few times from two different networks.

This error occurrs also at this moment, because the room is online.

**Comment by YamiOdymel** [comment]
> Maybe they changed something or the room video format is incompatible. Please, do you also see the error ?

It runs fine on my computer, it makes me harder to debug now 😭

![image](https://user-images.githubusercontent.com/7308718/205925112-d66f78a8-3db6-45e6-98fc-6600a5ebeeb5.png)

**Comment by TamaTT** [comment]
Plese could you try with the room from my picture ?
Another rooms work fine.

**Comment by YamiOdymel** [comment]
Yea, the room seems a bit weird, I've already updated the program and see if it solves the problem?

https://github.com/teacat/chaturbate-dvr/blob/master/bin/windows/chaturbate-dvr.exe

Please redownload it again.

**Comment by TamaTT** [comment]
Still the problem occurs. But it is not important, I was just curious. probably weird room:

![image](https://user-images.githubusercontent.com/119944809/205929133-464a9e44-d5c4-4345-98bb-5335d0ee31b7.png)

**Comment by YamiOdymel** [comment]
Program updated again, the problem seems to be fixed ( _PLEASE_ 😭😭

Please download it from the `v0.8 Alpha` Release: https://github.com/teacat/chaturbate-dvr/archive/refs/tags/v0.8-alpha.zip

---

I've noticed that the Chaturbate sometimes returns a bad Playlist with 403 error (Forbidden).

I solved the problem by refreshing the channel page again to get another URL of the Playlist if that happened.

---

Also with this update the program no longer stores temporary junk segments (It will now be stored in RAM, yay 🥳 ).

If you had other problems just tell me.
