### ISSUE TITLE
Error: Video Stuttering when Recording

### ISSUE THREAD

**Issue by BlahBlah5309** [teacat/chaturbate-dvr#57]
I know it's not a playback issue because I can watch other .ts videos just fine, on the same and different video players, on the same and different devices. could it be a bandwidth thing? I've tinkered with other chaturbate DVR things and I haven't had this issue.

**Comment by YamiOdymel** [comment]
The program downloads video segments and combine into one large `.ts` file, this might happen if there was network lagging, and some segments were lost.

I used to fixed it by waiting for the next segment to be fetched unless timed out, can't think of how it still happened 🤔

**Comment by BlahBlah5309** [comment]
I see. will this occur if the computer's resources are too occupied while recording? sometimes I do other stuff while the recorder works in the background.

**Comment by YamiOdymel** [comment]
No, it's not related to computer resources.

**Comment by YamiOdymel** [comment]
oh no 💀
i don't have the issue with long video, this is a bit hard to reproduce and debug

**Comment by YamiOdymel** [comment]
![image](https://github.com/teacat/chaturbate-dvr/assets/7308718/7fb77285-166f-4b9c-9115-87aaa7bbc0ae)

Chaturbate DVR fetches the segment list every second, I'm guessing that Chaturbate DVR was fetching the segment list at the exact 'half-second' when Chaturbate was updating its list, and the offset led to discrepancies in the final video result.

I will seek for the solution, but I've been really busy lately, you will receive the issued closed email once it got fixed 😭

**Comment by YamiOdymel** [comment]
@fhb302 Chaturbate DVR only combines the segments and it doesn't do encode. The program you used supports `.mkv` and h265?

**Comment by YamiOdymel** [comment]
@wandersons13 Thanks for that, I can see frames were dropped/loss with PotPlayer

_(also I edited your comment to make sure you won't get banned for that, lmao_

**Comment by BlahBlah5309** [comment]
> I recorded a 4k video, but it also appear this problem, it usually stuck and repeat some clips. I recently switch to another program. At the same time, I hope it can add the support of .mkv and h265, it can save more space (30G vs 6G)

what program is that?

**Comment by SamirPRO1** [comment]
I realized this issue can be fixed by pausing the recording and resuming it, perhaps you could implement a code that detects these errors:
[2024-05-05 02:51:06] [WARN] segment #5297 not found in buffer, skipped
and when there are like more than 2 or 3 in a minute it "restarts" the recording, just like you would do manually

**Comment by YamiOdymel** [comment]
I kinda have a clue about why the stutter is happening... 

`chaturbate-dvr` has multiple fetchers that retrieve video segments in parallel, but they share the same data (variable). This makes it prone to being overridden by another fetcher, resulting in both fetchers fetching the same segment.

Should be fixed in 3 days, finally- I guess. 🥺

---

Related source code snippet: (BUG: `v.URI` is shared between fetchers)

https://github.com/teacat/chaturbate-dvr/blob/acb1dff0cc553a0af077166aab5e2e574802d1db/chaturbate/channel_internal.go#L290-L300

**Comment by YamiOdymel** [comment]
Fixed in [v1.0.5](https://github.com/teacat/chaturbate-dvr/releases/tag/v1.0.5)

![image](https://github.com/teacat/chaturbate-dvr/assets/7308718/12960fff-9e9a-4259-8bd2-0ae565da1eed)
